apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokendashboard-postgres
  namespace: my-namespace
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tokendashboard-postgres
  template:
    metadata:
      labels:
        app: tokendashboard-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: tokendashboard-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tokendashboard-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tokendashboard-postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: tokendashboard-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tokendashboard-postgres-service
  namespace: my-namespace
spec:
  selector:
    app: tokendashboard-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
