ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [de.neuland.tokendashboard.ApplicationKt.module]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/tokendashboard"
    url = ${?DATABASE_URL}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "postgres"
    password = ${?DATABASE_PASSWORD}
    allowDefaultCredentials = false
    allowDefaultCredentials = ${?ALLOW_DEFAULT_DB_CREDENTIALS}
    reportingTimeZone = "UTC"
    reportingTimeZone = ${?REPORTING_TIME_ZONE}
}
